```{r include=FALSE, cache=FALSE}

knitr::opts_chunk$set(
  warning   = FALSE
  ,message   = FALSE
  ,collapse  = TRUE
  ,cache     = TRUE
# ,out.width = "70%"
# ,fig.align = 'center'
# ,fig.width = 6
# ,fig.asp   = 0.618 # 1 / phi
# ,fig.show  = "hold"
)

list.of.packages <- c("ggplot2", "Rcpp", "rstanarm", "lme4", "mice", "VIM", "pander", "kableExtra",
                      "corrplot", "psych", "ggfortify", "GPArotation", "sjPlot", "gridExtra", "knitr", 
                      "ggmap", "spdep", "housingData", "Hmisc", "waffle", "ROCR", "caret", "ggjoy",
                      "stargazer", "missForest", "forestplot", "emo")
# issues with MKMisk requiring 'limma' which is in bioconductor
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages>0)){install.packages(new.packages)}

library(ggplot2)
library(gridExtra)
library(dplyr)
library(pander)
library(knitr)
library(kableExtra)

options(knitr.kable.NA = '', knitr.table.format = "html")
theme_set(theme_bw())

# loading data sets used in multiple chapters

depress <- read.delim("https://norcalbiostat.netlify.com/data/depress_081217.txt")
names(depress) <- tolower(names(depress))


load(url("https://norcalbiostat.netlify.com/data/addhealth_clean.Rdata"))
addhealth$smoke <- ifelse(addhealth$eversmoke_c=="Smoker", 1, 0)

fev <- read.delim("https://norcalbiostat.netlify.com/data/Lung_081217.txt", sep="\t", header=TRUE)

```
# (PART) Regression Modeling {-}

# Introduction {#reg-intro}

The general purpose of regression is to learn more about the relationship between several independent or predictor variables and a quantitative dependent variable. Multiple regression procedures are very widely used in research. In general, this inferential tool allows us to ask (and hopefully answer) the general question "_what is the best predictor of_...", and does “_additional variable A_” or “_additional variable B” confound the relationship between my explanatory and response variable?_” 

> * Educational researchers might want to learn about the best predictors of success in high-school. 
* Sociologists may want to find out which of the multiple social indicators best predict whether or not a new immigrant group will adapt to their new country of residence. 
* Biologists may want to find out which factors (i.e. temperature, barometric pressure, humidity, etc.) best predict caterpillar reproduction.

This chapter starts by recapping notation and topics for simple linear regression, when there is only one predictor. Then we move into generalization of these concepts to many predictors, and model building topics such as stratification, interactions, and categorical predictors. 

